# Generated by Django 4.2 on 2023-07-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='img',
            field=models.ImageField(default='abcd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
